language: scala

dist: xenial

sudo: false

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/launchers
    - $HOME/.cache/coursier

scala:
  - 2.11.12
  - 2.12.11
  - 2.13.2

script:
  - git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
  - git show --oneline --check
  - wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376edf/sbt && chmod +x ./sbt
  - ./sbt "++${TRAVIS_SCALA_VERSION}!" scalafmtCheck test:scalafmtCheck scalafmtSbtCheck checkGenerateCodeError compile test:compile testSequential publishLocal
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm
  - find $HOME/.ivy2/cache -name "*SNAPSHOT*" | xargs rm -rf

matrix:
  include:
    - scala: 2.12.11
      jdk: openjdk11
    - scala: 2.11.12
      jdk: openjdk8
      sudo: required
      env: SCALA_NATIVE=true
      before_install:
      - curl https://raw.githubusercontent.com/scala-native/scala-native/master/scripts/travis_setup.sh | bash -x
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376edf/sbt && chmod +x ./sbt
      script:
      - ./sbt ++$TRAVIS_SCALA_VERSION msgpack4z-coreNative/test
    - os: windows
      language: bash
      env: JDK="adopt@1.8.0-222"
      before_script:
      - wget https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh
      - source .install-jdk-travis.sh
      - wget https://raw.githubusercontent.com/paulp/sbt-extras/3c8fcadc3376edf/sbt && chmod +x ./sbt
      script:
      - ./sbt "++ 2.13.2" msgpack4z-coreJVM/test testJava07/test testJavaLatest/test
