name: CI
on:
  pull_request:
  push:
  schedule:
  - cron: '0 17 * * 1'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: jvm-js
          - name: scala-native
    steps:
    - uses: actions/checkout@v1
    - uses: olafurpg/setup-scala@v10
      with:
        java-version: "adopt@1.8"
    - uses: coursier/cache-action@v5
    - run: git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
    - run: git show --oneline --check
    - run: if [[ "${{ matrix.name }}" == "scala-native" ]] ; then ./.github/scala-native-setup.sh ; fi
    - run:  |
        case ${{ matrix.name }} in
          "jvm-js")
            sbt -v
            scalafmtCheckAll
            scalafmtSbtCheck
            checkGenerateCodeError
            "+ test:compile"
            testSequentialCross
            "+ publishLocal"
            ;;
          "scala-native")
            sbt -v msgpack4z-coreNative/test
            ;;
          *)
            echo "unknown job-name"
            exit 1
        esac
