name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        java:
          - 17
          - 25
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - shell: bash
      name: install sbt
      run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/aff36a23f7213d94189aabfcc47a32b11f3a6fba/sbt > ./sbt && chmod 0755 ./sbt
    - uses: coursier/cache-action@v8
    - run: git config core.whitespace tab-in-indent,trailing-space,space-before-tab,cr-at-eol
    - run: git show --oneline --check
    - run:  |
       ./sbt -v \
       scalafmtCheckAll \
       scalafmtSbtCheck \
       checkGenerateCodeError \
       Test/compile \
       testSequential \
       publishLocal
    - run: rm -rf ~/.ivy2/local
  latest:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-java@v5
      with:
        java-version: 25
        distribution: zulu
    - shell: bash
      run: curl -Ls https://raw.githubusercontent.com/dwijnand/sbt-extras/b65ba508d917b2897/sbt > ./sbt && chmod 0755 ./sbt
    - uses: coursier/cache-action@v8
    - run:
       ./sbt -v
       '++ 3.9.0-RC1!'
       msgpack4z-coreJVM3/test
       msgpack4z-coreJS3/test
       msgpack4z-coreNative3/test
       testJavaLatest3/test
       "all msgpack4z-coreJVM3/publishLocal msgpack4z-coreJS3/publishLocal msgpack4z-coreNative3/publishLocal"
    - run: rm -rf ~/.ivy2/local
